export const copy = {
  brand: "Forge Regex",
  navPricing: "Pricing",
  navUpgrade: "Upgrade",
  navOpenApp: "Open app",
  navSignIn: "Sign in",
  navSignOut: "Sign out",
  proUnlimited: "Pro — unlimited generations",
  freeLeft: "{n} free left",
  guestLeft: "{n} trial left",
  freeResetDaily: "Resets daily (UTC) for your signed-in email",
  heroTitle: "Describe your pattern.\nGet the regex.",
  heroReady: "Your regex is ready",
  heroSub:
    "Stop wrestling with regex syntax. Say what you want to match — we'll forge a working expression.",
  promptPlaceholder: "e.g. match emails, or phone numbers…",
  promptLabel: "Describe what you want to match",
  generate: "Generate",
  forging: "Forging…",
  forgingHint: "Writing a production-ready pattern…",
  examples: "Examples",
  generatedRegex: "Generated regex",
  copy: "Copy",
  copied: "Copied",
  howItWorks: "How it works",
  testTitle: "Test against your text",
  matches: "{n} matches",
  matchOne: "1 match",
  matchZero: "0 matches",
  noMatchesHint: "No matches in this text yet – try editing the sample.",
  flagsLabel: "Flags",
  capturesTitle: "Capture groups",
  captureDash: "—",
  redosTitle: "This pattern may be slow or unsafe on some inputs (ReDoS risk).",
  redosNested: "A quantified group contains another quantifier (e.g. (a+)+). Prefer a tighter pattern.",
  redosAdjacent: "Adjacent overlapping quantifiers can backtrack heavily. Tighten the pattern if you can.",
  redosOptional: "An optional group wrapping a quantifier can explode on crafted input. Consider rewriting.",
  unlimitedPro: "Unlimited with Pro",
  proBadge: "Pro",
  pricingTitle: "Simple pricing",
  pricingSub:
    "Try 2 times without signing in; free accounts get 8/day after email sign-in. Upgrade for unlimited.",
  planFree: "Free",
  planPro: "Pro",
  perForever: "/ forever",
  perMonth: "/ month",
  freeFeat1: "2 guest tries, then 8 AI generations per day signed in",
  freeFeat2: "Live match testing",
  freeFeat3: "Token-by-token explanations",
  errSignInToGenerate: "Trial used up. Sign in for 8 generations per day.",
  proFeat1: "Unlimited generations",
  proFeat2: "Share links & history",
  proFeat3: "Priority model access",
  proFeat4: "Email support",
  startGenerating: "Start generating",
  payGo: "Subscribe — $9/mo",
  billingNote:
    "Payments processed by Paddle.com as Merchant of Record (card, PayPal, and other local methods by region).",
  replaceTitle: "Replace",
  replaceLabel: "Replacement",
  replaceCopy: "Copy replaced text",
  replaceEmpty: "Nothing to preview yet",
  exportTitle: "Export",
  exportCopy: "Copy snippet",
  share: "Share",
  shareLink: "Public link",
  shareCopyLink: "Copy link",
  shareProOnly:
    "Sharing is a Pro feature. Sign in and upgrade to create a public link with your prompt, regex, and test text.",
  shareFailed: "Could not create share link.",
  myShares: "My shares",
  sharesTitle: "My shares",
  sharesEmpty: "No shares yet. Generate a regex and click Share.",
  sharesDelete: "Delete",
  shareOpenInForge: "Open in Forge",
  shareNotFound: "This share link was not found or was deleted.",
  footerPricing: "Pricing",
  footerPatterns: "Patterns",
  footerPrivacy: "Privacy",
  footerTerms: "Terms",
  footerRefunds: "Refunds",
  footerContact: "Contact",
  authWelcome: "Welcome back",
  authRegisterTitle: "Create account",
  authForgotTitle: "Reset password",
  authCodeTitle: "Enter verification code",
  authCopy:
    "Sign in with email and password. Guests get 2 free tries; signed-in free accounts get 8 AI generations per day; Pro is unlimited.",
  authRegisterCopy:
    "Create an account with email and password. We’ll email a 6-digit code to verify.",
  authForgotCopy: "Enter your email and we’ll send a code to reset your password.",
  authCodeCopy: "Enter the 6-digit code we sent to your email.",
  authEmail: "Email",
  authPassword: "Password",
  authConfirmPassword: "Confirm password",
  authCode: "Verification code",
  authLogin: "Sign in",
  authRegister: "Register",
  authForgot: "Forgot password?",
  authSendCode: "Send code",
  authVerify: "Verify & continue",
  authReset: "Set new password",
  authResend: "Resend code",
  authResendIn: "Resend in {n}s",
  authBackLogin: "Back to sign in",
  authSending: "Sending…",
  authWorking: "Please wait…",
  authPasswordMismatch: "Passwords do not match.",
  authPasswordShort: "Password must be at least 8 characters.",
  authDevCode: "Dev code (email not configured):",
  authClose: "Close",
  authCheckInbox: "Check your inbox",
  authContinue: "Continue",
  authSentTo: "We sent a code to",
  authHint: "The code expires in 10 minutes.",
  authDifferent: "Use a different email",
  loadingCheckout: "Loading checkout…",
  checkoutNotConfigured: "Checkout not configured",
  networkError: "Network error. Try again.",
  somethingWentWrong: "Something went wrong. Please try again.",
  proUnlimitedFooter: "Pro — unlimited generations",
  emptyHint: "Type a description above, or pick an example to see Forge in action.",
  startWithGenerate: "Start with Generate",
  freeGensToday: "{used}/{limit} free generations today",
  errSignInRequired: "Sign in required.",
  errProRequired: "Pro required.",
  errShareNeedsPro: "Sharing requires Pro. Upgrade to create a public link.",
  errPatternRequired: "Pattern is required.",
} as const;

export type MessageKey = keyof typeof copy;

export function t(
  key: MessageKey,
  vars?: Record<string, string | number>
): string {
  const template = copy[key] ?? key;
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, name: string) =>
    vars[name] !== undefined ? String(vars[name]) : `{${name}}`
  );
}
